### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by pedroa75** [g200kg/zoom-ms-utility#2]
Hi,

First of all thank you very much for this brilliant utility. 
Loved the webpage app concept, so there is no need to install anything on your OS.

Is it possible to use the editor offline?

I tried simply saving the page and run it offline, it does not show the welcome page, and it says:

> Another Patch Editor is launched.
> This instance is no more effective. 
> Reload?

With an "ok" button, when clicked it does nothing.

I also tried downloading the whole github repository, and run the index html file, and though it shows the initial welcome page, as soon as you authorize midi access it will give the same error.

Even if I run the html page online it gives the same error.

Again than you very much for this application, it is really really useful.

Keep up the good work.

**Comment by worldeggplant** [comment]
@pedroa75 You need to run this through a web server.

If you have Python installed, you can run the following command in a terminal to start one:
````
$ cd zoom-ms-utility-master
$ python -m SimpleHTTPServer
````

And then go to http://localhost:8000/

The longer answer for this is that the app uses Polymer which in turn uses XHR which requires CORS to be allowed by the server, which by default is restricted in (most?) web browsers for the file protocol.

**Comment by pedroa75** [comment]
@worldeggplant Thank you very much.

As soon as I placed it on htdocs of my apache server, on a wamp stack, and access it through localhost it started working alright.

Cool :)

Cheers
